/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudoku;

import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Hp
 */
public class PRINCIPAL extends javax.swing.JFrame {
    Sudoku sudo=new Sudoku();
    private JTextField label[][];
    int inicial[][]=new int[9][9];
    int partida[][]=new int[9][9];
    int restablecer[][]=new int[9][9];
    /**
     * Creates new form PRINCIPAL
     */
    public PRINCIPAL() {
        initComponents();
        this.label = new JTextField[9][9];
        Component[] lista = contenedor.getComponents();

        String s, fs, cs;
        int f, c;

        for (Component lb : lista) {
            s = lb.getName();

            fs = s.substring(0, 1);
            cs = s.substring(1, 2);

            f = Integer.parseInt(fs);
            c = Integer.parseInt(cs);
            this.label[f][c] = (JTextField) lb;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        bt_generar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        contenedor = new javax.swing.JPanel();
        j08 = new javax.swing.JTextField();
        j07 = new javax.swing.JTextField();
        j06 = new javax.swing.JTextField();
        j16 = new javax.swing.JTextField();
        j17 = new javax.swing.JTextField();
        j18 = new javax.swing.JTextField();
        j28 = new javax.swing.JTextField();
        j27 = new javax.swing.JTextField();
        j26 = new javax.swing.JTextField();
        j36 = new javax.swing.JTextField();
        j37 = new javax.swing.JTextField();
        j38 = new javax.swing.JTextField();
        j48 = new javax.swing.JTextField();
        j47 = new javax.swing.JTextField();
        j46 = new javax.swing.JTextField();
        j56 = new javax.swing.JTextField();
        j57 = new javax.swing.JTextField();
        j58 = new javax.swing.JTextField();
        j68 = new javax.swing.JTextField();
        j67 = new javax.swing.JTextField();
        j66 = new javax.swing.JTextField();
        j76 = new javax.swing.JTextField();
        j77 = new javax.swing.JTextField();
        j78 = new javax.swing.JTextField();
        j88 = new javax.swing.JTextField();
        j87 = new javax.swing.JTextField();
        j86 = new javax.swing.JTextField();
        j05 = new javax.swing.JTextField();
        j04 = new javax.swing.JTextField();
        j03 = new javax.swing.JTextField();
        j13 = new javax.swing.JTextField();
        j14 = new javax.swing.JTextField();
        j15 = new javax.swing.JTextField();
        j25 = new javax.swing.JTextField();
        j24 = new javax.swing.JTextField();
        j23 = new javax.swing.JTextField();
        j35 = new javax.swing.JTextField();
        j34 = new javax.swing.JTextField();
        j33 = new javax.swing.JTextField();
        j43 = new javax.swing.JTextField();
        j44 = new javax.swing.JTextField();
        j45 = new javax.swing.JTextField();
        j55 = new javax.swing.JTextField();
        j54 = new javax.swing.JTextField();
        j53 = new javax.swing.JTextField();
        j65 = new javax.swing.JTextField();
        j64 = new javax.swing.JTextField();
        j63 = new javax.swing.JTextField();
        j73 = new javax.swing.JTextField();
        j74 = new javax.swing.JTextField();
        j75 = new javax.swing.JTextField();
        j85 = new javax.swing.JTextField();
        j84 = new javax.swing.JTextField();
        j83 = new javax.swing.JTextField();
        j02 = new javax.swing.JTextField();
        j01 = new javax.swing.JTextField();
        j00 = new javax.swing.JTextField();
        j10 = new javax.swing.JTextField();
        j11 = new javax.swing.JTextField();
        j12 = new javax.swing.JTextField();
        j22 = new javax.swing.JTextField();
        j21 = new javax.swing.JTextField();
        j20 = new javax.swing.JTextField();
        j32 = new javax.swing.JTextField();
        j31 = new javax.swing.JTextField();
        j30 = new javax.swing.JTextField();
        j40 = new javax.swing.JTextField();
        j41 = new javax.swing.JTextField();
        j42 = new javax.swing.JTextField();
        j52 = new javax.swing.JTextField();
        j51 = new javax.swing.JTextField();
        j50 = new javax.swing.JTextField();
        j62 = new javax.swing.JTextField();
        j61 = new javax.swing.JTextField();
        j60 = new javax.swing.JTextField();
        j70 = new javax.swing.JTextField();
        j71 = new javax.swing.JTextField();
        j72 = new javax.swing.JTextField();
        j82 = new javax.swing.JTextField();
        j81 = new javax.swing.JTextField();
        j80 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("SUDOKU");

        bt_generar.setText("Generar");
        bt_generar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_generarActionPerformed(evt);
            }
        });

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        j08.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j08.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j08.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j08.setName("08"); // NOI18N
        j08.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j07.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j07.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j07.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j07.setName("07"); // NOI18N
        j07.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j06.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j06.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j06.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j06.setName("06"); // NOI18N
        j06.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j16.setName("16"); // NOI18N
        j16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j17.setName("17"); // NOI18N
        j17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j18.setName("18"); // NOI18N
        j18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j28.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j28.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j28.setName("28"); // NOI18N
        j28.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j27.setName("27"); // NOI18N
        j27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j26.setName("26"); // NOI18N
        j26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j36.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j36.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j36.setName("36"); // NOI18N
        j36.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j37.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j37.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j37.setName("37"); // NOI18N
        j37.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j38.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j38.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j38.setName("38"); // NOI18N
        j38.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j48.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j48.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j48.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j48.setName("48"); // NOI18N
        j48.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j47.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j47.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j47.setName("47"); // NOI18N
        j47.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j46.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j46.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j46.setName("46"); // NOI18N
        j46.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j56.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j56.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j56.setName("56"); // NOI18N
        j56.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j57.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j57.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j57.setName("57"); // NOI18N
        j57.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j58.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j58.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j58.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j58.setName("58"); // NOI18N
        j58.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j68.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j68.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j68.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j68.setName("68"); // NOI18N
        j68.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j67.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j67.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j67.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j67.setName("67"); // NOI18N
        j67.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j66.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j66.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j66.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j66.setName("66"); // NOI18N
        j66.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j76.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j76.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j76.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j76.setName("76"); // NOI18N
        j76.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j77.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j77.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j77.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j77.setName("77"); // NOI18N
        j77.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j78.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j78.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j78.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j78.setName("78"); // NOI18N
        j78.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j88.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j88.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j88.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j88.setName("88"); // NOI18N
        j88.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j87.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j87.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j87.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j87.setName("87"); // NOI18N
        j87.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j86.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j86.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j86.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j86.setName("86"); // NOI18N
        j86.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j05.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j05.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j05.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j05.setName("05"); // NOI18N
        j05.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j04.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j04.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j04.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j04.setName("04"); // NOI18N
        j04.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j03.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j03.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j03.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j03.setName("03"); // NOI18N
        j03.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j13.setName("13"); // NOI18N
        j13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j14.setName("14"); // NOI18N
        j14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j15.setName("15"); // NOI18N
        j15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j25.setName("25"); // NOI18N
        j25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j24.setName("24"); // NOI18N
        j24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j23.setName("23"); // NOI18N
        j23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j35.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j35.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j35.setName("35"); // NOI18N
        j35.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j34.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j34.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j34.setName("34"); // NOI18N
        j34.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j33.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j33.setName("33"); // NOI18N
        j33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j43.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j43.setName("43"); // NOI18N
        j43.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j44.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j44.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j44.setName("44"); // NOI18N
        j44.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j45.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j45.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j45.setName("45"); // NOI18N
        j45.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j55.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j55.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j55.setName("55"); // NOI18N
        j55.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j54.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j54.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j54.setName("54"); // NOI18N
        j54.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j53.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j53.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j53.setName("53"); // NOI18N
        j53.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j65.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j65.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j65.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j65.setName("65"); // NOI18N
        j65.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j64.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j64.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j64.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j64.setName("64"); // NOI18N
        j64.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j63.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j63.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j63.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j63.setName("63"); // NOI18N
        j63.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j73.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j73.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j73.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j73.setName("73"); // NOI18N
        j73.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j74.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j74.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j74.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j74.setName("74"); // NOI18N
        j74.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j75.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j75.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j75.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j75.setName("75"); // NOI18N
        j75.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j85.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j85.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j85.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j85.setName("85"); // NOI18N
        j85.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j84.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j84.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j84.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j84.setName("84"); // NOI18N
        j84.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j83.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j83.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j83.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j83.setName("83"); // NOI18N
        j83.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j02.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j02.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j02.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j02.setName("02"); // NOI18N
        j02.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j01.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j01.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j01.setName("01"); // NOI18N
        j01.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j00.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j00.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j00.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j00.setName("00"); // NOI18N
        j00.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j10.setName("10"); // NOI18N
        j10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j11.setName("11"); // NOI18N
        j11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j12.setName("12"); // NOI18N
        j12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j22.setName("22"); // NOI18N
        j22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j21.setName("21"); // NOI18N
        j21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j20.setName("20"); // NOI18N
        j20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j32.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j32.setName("32"); // NOI18N
        j32.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j31.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j31.setName("31"); // NOI18N
        j31.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j30.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j30.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j30.setName("30"); // NOI18N
        j30.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j40.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j40.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j40.setName("40"); // NOI18N
        j40.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j41.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j41.setName("41"); // NOI18N
        j41.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j42.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j42.setName("42"); // NOI18N
        j42.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j52.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j52.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j52.setName("52"); // NOI18N
        j52.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j51.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j51.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j51.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j51.setName("51"); // NOI18N
        j51.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j50.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j50.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j50.setName("50"); // NOI18N
        j50.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j62.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j62.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j62.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j62.setName("62"); // NOI18N
        j62.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j61.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j61.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j61.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j61.setName("61"); // NOI18N
        j61.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j60.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j60.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j60.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j60.setName("60"); // NOI18N
        j60.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j70.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j70.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j70.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j70.setName("70"); // NOI18N
        j70.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j71.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j71.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j71.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j71.setName("71"); // NOI18N
        j71.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j72.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j72.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j72.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j72.setName("72"); // NOI18N
        j72.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j82.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j82.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j82.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j82.setName("82"); // NOI18N
        j82.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j81.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j81.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j81.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j81.setName("81"); // NOI18N
        j81.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        j80.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        j80.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        j80.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        j80.setName("80"); // NOI18N
        j80.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                KeyJtextField(evt);
            }
        });

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j00, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j01, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j02, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j03, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j04, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j05, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j82, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j83, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j84, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j85, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(6, 6, 6)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j06, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j07, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j08, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addComponent(j86, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j87, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(j88, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(j06, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j07, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j08, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(j16, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j17, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j18, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(j26, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j27, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j28, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(j03, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j04, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j05, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(j13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j14, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j15, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(j23, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j24, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(j25, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j00, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j01, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j02, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j20, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j21, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j22, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j36, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j37, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j38, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j46, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j47, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j48, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j56, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j57, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j58, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(contenedorLayout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j30, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j31, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j32, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j40, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j41, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j42, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(j50, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j51, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(j52, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j34, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j35, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j43, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j44, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j45, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j53, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j54, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j55, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j66, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j67, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j68, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j76, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j77, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j78, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j86, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j87, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j88, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(contenedorLayout.createSequentialGroup()
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j63, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j64, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j65, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j73, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j74, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j75, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(j83, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j84, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(j85, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(contenedorLayout.createSequentialGroup()
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j60, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j61, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j62, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j70, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j71, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j72, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j80, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j81, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(j82, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bt_generar)
                        .addGap(66, 66, 66)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(contenedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_generar)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_generarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_generarActionPerformed
        inicial=sudo.generarInicial(inicial);
        for(int i=0; i<9; i++){
            for(int j=0; j<9;j++){
                partida[i][j]=inicial[i][j];
            }
        }
        partida=sudo.generarPartida(partida);
        partida=sudo.generarPartida(partida);
        partida=sudo.generarPartida(partida);
        for(int i=0; i<9; i++){
            for(int j=0; j<9;j++){
                restablecer[i][j]=partida[i][j];
            }
        }
        for(int i=0; i<9; i++){
            for(int j=0; j<9;j++){
                if(partida[i][j]!=0){
                    label[i][j].setText(""+partida[i][j]);
                    label[i][j].setForeground(Color.BLUE);
                    label[i][j].setEnabled(false);
                }
            }
        }
        sudo.imprimir(partida);
    }//GEN-LAST:event_bt_generarActionPerformed

    private void KeyJtextField(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_KeyJtextField
//        boolean terminado=false;
        JTextField btn = (JTextField) evt.getSource();

        String s = btn.getName();

        int f = Integer.parseInt(s.substring(0, 1));
        int c = Integer.parseInt(s.substring(1, 2));
        int numero=(int)evt.getKeyChar()-48;
        if(numero<0)
            numero=0;
        System.out.println(numero);
        label[f][c].setForeground(Color.BLACK);
        if(sudo.comprobardato(partida,numero,f,c)){
            label[f][c].setForeground(Color.GREEN);
            System.out.println("Valido");
        }
        else{
            label[f][c].setForeground(Color.RED);
            System.out.println("No Valido");
        }
        partida[f][c]=numero;
        if(sudo.terminado(partida)){
            finalizar();
            JOptionPane.showMessageDialog(null, "Juego Terminado");
        }
        sudo.imprimir(partida);
    }//GEN-LAST:event_KeyJtextField
    public void finalizar(){
        for(int i=0; i<9; i++){
            for(int j=0; j<9;j++){
                label[i][j].setEditable(false);
            }
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PRINCIPAL.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PRINCIPAL().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_generar;
    private javax.swing.JPanel contenedor;
    private javax.swing.JTextField j00;
    private javax.swing.JTextField j01;
    private javax.swing.JTextField j02;
    private javax.swing.JTextField j03;
    private javax.swing.JTextField j04;
    private javax.swing.JTextField j05;
    private javax.swing.JTextField j06;
    private javax.swing.JTextField j07;
    private javax.swing.JTextField j08;
    private javax.swing.JTextField j10;
    private javax.swing.JTextField j11;
    private javax.swing.JTextField j12;
    private javax.swing.JTextField j13;
    private javax.swing.JTextField j14;
    private javax.swing.JTextField j15;
    private javax.swing.JTextField j16;
    private javax.swing.JTextField j17;
    private javax.swing.JTextField j18;
    private javax.swing.JTextField j20;
    private javax.swing.JTextField j21;
    private javax.swing.JTextField j22;
    private javax.swing.JTextField j23;
    private javax.swing.JTextField j24;
    private javax.swing.JTextField j25;
    private javax.swing.JTextField j26;
    private javax.swing.JTextField j27;
    private javax.swing.JTextField j28;
    private javax.swing.JTextField j30;
    private javax.swing.JTextField j31;
    private javax.swing.JTextField j32;
    private javax.swing.JTextField j33;
    private javax.swing.JTextField j34;
    private javax.swing.JTextField j35;
    private javax.swing.JTextField j36;
    private javax.swing.JTextField j37;
    private javax.swing.JTextField j38;
    private javax.swing.JTextField j40;
    private javax.swing.JTextField j41;
    private javax.swing.JTextField j42;
    private javax.swing.JTextField j43;
    private javax.swing.JTextField j44;
    private javax.swing.JTextField j45;
    private javax.swing.JTextField j46;
    private javax.swing.JTextField j47;
    private javax.swing.JTextField j48;
    private javax.swing.JTextField j50;
    private javax.swing.JTextField j51;
    private javax.swing.JTextField j52;
    private javax.swing.JTextField j53;
    private javax.swing.JTextField j54;
    private javax.swing.JTextField j55;
    private javax.swing.JTextField j56;
    private javax.swing.JTextField j57;
    private javax.swing.JTextField j58;
    private javax.swing.JTextField j60;
    private javax.swing.JTextField j61;
    private javax.swing.JTextField j62;
    private javax.swing.JTextField j63;
    private javax.swing.JTextField j64;
    private javax.swing.JTextField j65;
    private javax.swing.JTextField j66;
    private javax.swing.JTextField j67;
    private javax.swing.JTextField j68;
    private javax.swing.JTextField j70;
    private javax.swing.JTextField j71;
    private javax.swing.JTextField j72;
    private javax.swing.JTextField j73;
    private javax.swing.JTextField j74;
    private javax.swing.JTextField j75;
    private javax.swing.JTextField j76;
    private javax.swing.JTextField j77;
    private javax.swing.JTextField j78;
    private javax.swing.JTextField j80;
    private javax.swing.JTextField j81;
    private javax.swing.JTextField j82;
    private javax.swing.JTextField j83;
    private javax.swing.JTextField j84;
    private javax.swing.JTextField j85;
    private javax.swing.JTextField j86;
    private javax.swing.JTextField j87;
    private javax.swing.JTextField j88;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
